sudo: required
group: deprecated-2017Q2

services:
  - docker

before_install:
  - docker pull alpine:3.6

install:
  - travis_wait docker build --tag bodsch/docker-grafana .
  - docker run --detach --name grafana bodsch/docker-grafana

script:
  - docker ps | grep -q grafana

notifications:
  email:
    - bodo@boone-schulz.de
