sudo: required
group: deprecated-2017Q2

services:
  - docker

before_install:
  - docker pull alpine:3.6

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - docker ps | grep -q grafana

before_script:
  - docker --version  # document the version travis is using
  - echo "#### Disk usage before running script:";
  - df -h;
  - du . | sort -nr | head -n100

after_success:
  - echo "#### Build successful; Disk usage after running script:";
  - df -h;
  - du . | sort -nr | head -n100
  - travis_retry 5 docker build --tag bodsch/docker-grafana .
  - docker run --detach --name grafana bodsch/docker-grafana

after_failure:
  - echo "#### Build failed; Disk usage after running script:";
  - df -h;
  - du . | sort -nr | head -n100
  - dmesg | grep -i kill

notifications:
  email: false

cache:
  directories:
    - $HOME/docker
