---
version: '2.0'

volumes:
  database:

networks:
  mon:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

services:

  grafana:
    restart: always
    build: .
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    extends:
      file: environment.yml
      service: grafana
    depends_on:
      - database
    links:
      - database
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/docker-data/icinga2-master:/srv
    networks:
      mon:
        ipv4_address: 192.168.10.10

  database:
    restart: always
    image: bodsch/docker-mysql:1707-27.1
    container_name: database
    hostname: database
    ports:
      - 3306:3306
    extends:
      file: environment.yml
      service: database
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - database:/srv
    networks:
      mon:
        ipv4_address: 192.168.10.5