---
version: '2.0'

services:
  grafana:
    restart: always
    build: .
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      URL_PATH: /
      # DATABASE_TYPE: mysql
      # MYSQL_HOST: database
      # MYSQL_PORT: 3306
      # MYSQL_ROOT_USER: root
      # MYSQL_ROOT_PASS: database.pass
      # CARBON_HOST: carbon
      # CARBON_PORT: 2003
      # MEMCACHE_HOST: memcached
      # MEMCACHE_PORT: 11211
      # DATABASE_GRAFANA_PASS: grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/docker-data/grafana:/srv
